variables:
  POSTGRES_DATABASE: ${POSTGRES_DATABASE}
  POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  SERVER_ADDRESS: ${SERVER_ADDRESS}